[tool.ruff]
line-length = 100
exclude = [".git", "__pycache__", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "W", "C"]
per-file-ignores = { "__init__.py" = ["F401"] }
ignore = [
    "D100", # Missing docstring in public module
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
