[tool.ruff]
line-length = 100
exclude = [".git", "__pycache__", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "W", "C"]
per-file-ignores = { "__init__.py" = ["F401"] }

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
